### ISSUE TITLE
Add a clear procedure to launch the project

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#1]
## Quest:
We need to include a step-by-step guide in the documentation that explains how to clone, configure, and run the project. This will help new contributors quickly get the project running in their local environment.

## Task:

- [x] Document the prerequisites (JDK, Maven, Docker, etc.).

- [x] Provide steps for cloning the repository and setting up environment variables.

- [x] Include instructions to start MongoDB (use Docker).

- [x] Detail how to install dependencies and run the project using Maven or an IDE.

- [x] Add a section for testing the API using Postman (JWT tokens, authentication).

![image](https://github.com/user-attachments/assets/e270dca7-8b75-4603-ac69-982d63108ab7)

The keeper of the repo 🏰
