### ISSUE TITLE
Write Unit Tests for AuthenticationService

### ISSUE THREAD

**Issue by LeNelSoN** [LeNelSoN/you-are-the-hero#10]
## Quest:
Develop unit tests for the `AuthenticationService` class to ensure that user authentication works correctly and that JWTs are generated as expected.

## Tasks:

Test `authenticateUser` Method:

- [ ] Verify that a valid username and password successfully authenticate the user and return a JWT.
- [ ] Ensure that it throws an exception when the username or password is invalid, indicating authentication failure.
- [ ] Validate that the method calls the authenticationManager and userDetailsService appropriately during the authentication process.
- [ ] Check that the generated token is valid and contains the expected username.

![image](https://github.com/user-attachments/assets/85618cca-3194-430f-88ba-d575694f3698)

The keeper of the repo 🏰

**Comment by padabou** [comment]
I'll take this one

**Comment by padabou** [comment]
Check that the generated token is valid and contains the expected username. ==> This is not a unit test because this feature is managed by another class
